steps:
   - name: gcr.io/cloud-builders/gcloud
     args:
     - kms
     - decrypt
     - --ciphertext-file=.env.enc
     - --plaintext-file=.env
     - --location=global
     - --keyring=$_KEY_RING
     - --key=$_KEY_NAME
 # Build the container image
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/$PROJECT_ID/kutuka-bombay:$TAG_NAME', '.']
 # Push the image to Container Registry
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/$PROJECT_ID/kutuka-bombay:$TAG_NAME']
 # Deploy image to Cloud Run
   - name: 'gcr.io/cloud-builders/gcloud'
     args:
     - 'run'
     - 'deploy'
     - 'kutuka-bombay'
     - '--image'
     - 'gcr.io/$PROJECT_ID/kutuka-bombay:$TAG_NAME'
     - '--region'
     - 'us-east1'
     - '--platform'
     - 'managed'
images:
   - gcr.io/$PROJECT_ID/kutuka-bombay:$TAG_NAME
 